### ISSUE TITLE
Beginner Class: InSpec control structure using tags for `check` and `fix`

### ISSUE THREAD

**Issue by karikarshivani** [mitre/saf-training#228]
Keywords used before `check` and `fix` in the [InSpec control structure section](https://mitre.github.io/saf-training/courses/beginner/02.html#inspec-controls-structure) need to be changed from `tag` to `desc`:

![Screenshot 2024-10-09 at 11 31 04 AM](https://github.com/user-attachments/assets/4c3ec303-5f0b-4f88-acf2-0d7bb975f14d)

**Comment by p-oneil** [comment]
Corrected in recent commit

https://github.com/mitre/saf-training/commit/d100c983f57716274bd7ee6ec2658eecd75dfacc
